### ISSUE TITLE
An exception raises while processing PPTX presentation

### ISSUE THREAD

**Issue by aleksandarvidakovicaspose** [groupdocs-viewer/GroupDocs.Viewer-for-.NET-WebForms#38] opened 2019-02-15 01:04 UTC
Hi,

Please notice that an exception raises while opening the presentation (test.pptx).
Since the presentation contains a customer's confidential data, it has been zipped with a password.
Please keep in mind that as soon as the issue is assigned to someone, I will send the password.
The file can be download using the following link, 
https://drive.google.com/open?id=1dTa-5t_Kq8bKsVegKwYxvKggnTgASSux

The screenshot of the exception is attached below.
![exception](https://user-images.githubusercontent.com/41449852/52827636-f1818a80-30c5-11e9-824b-eafe4c71080b.png)

Best Regards.

**Comment by Pavel-Teplitsky** [comment] 2019-02-15 05:57
@aleksandarvidakovicaspose Thank you for the request. Please share the password, you can send it to my email pavel.teplitsky@aspose.com

Thank you.

**Comment by Pavel-Teplitsky** [comment] 2019-02-16 14:46
@aleksandarvidakovicaspose  I checked the issue and was able to view document successfully in both modes (HTML and Image), screenshots files shared with you via email. Please make sure that you use latest version of the example. Also could you please share configurations from your configuration.yml file.

**Comment by aleksandarvidakovicaspose** [comment] 2019-02-18 01:12
Hi @Pavel-Teplitsky,
Please find the configuration.yml(just remove .zip extension
[GroupDocs.Viewer-for-.NET-WebForms.zip](https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET-WebForms/files/2873660/GroupDocs.Viewer-for-.NET-WebForms.zip)
) in the attachment.
Also, just for the sake of clarity,
[configuration.yml.zip](https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET-WebForms/files/2873659/configuration.yml.zip)
the sample project used at my side is shared. 
Best Regards.

**Comment by Pavel-Teplitsky** [comment] 2019-02-18 06:20
Hi @aleksandarvidakovicaspose Thank you for sharing sources. I will check them and return to you.

Best regards.

**Comment by Pavel-Teplitsky** [comment] 2019-02-18 08:44
Hi @aleksandarvidakovicaspose I have investigated the issue using your configuration properties and found out that the exception thrown if to set "preloadPageCount" property. If to set mentioned property GroupDocs.Viewer product (not the example it self) fails to load document pages. I have created a bug ticket for GroupDocs.Viewer product team with highest priority, when they will fix the issue I will notify you here.

Best regards

**Comment by Pavel-Teplitsky** [comment] 2019-02-19 09:59
Although we still investigating the root cause of this issue we found following workaround: 

Switch IIS to 64-bit mode. 
In the Visual studio navigate to Tools -> Options -> Project and Solutions -> Web Projects and check "Use 64 bit version of IIS Express for web sites and projects" option.

Let us know if it works for you.

**Comment by aleksandarvidakovicaspose** [comment] 2019-02-19 14:08
Hi @Pavel-Teplitsky,
Thanks for sharing additional insight. It seems that IIS Express worked in 32-bit mode which prevented allocating of RAM more than 2GB.
Best Regards.

**Comment by Pavel-Teplitsky** [comment] 2019-02-19 14:58
@aleksandarvidakovicaspose Thank you for this information. Can I close this issue?

**Closed** 2019-02-21 06:18 UTC
Labels: bug
